- name: Deploy insights
  hosts: insights
  become: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    disable_edx_services: false
    ENABLE_DATADOG: False
    ENABLE_SPLUNKFORWARDER: False
    ENABLE_NEWRELIC: False
  roles:
    - role: nginx
      nginx_sites:
        - insights
    - insights
