- name: Deploy all analytics mysql, memcache
  hosts: analytics_mysql
  become: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    disable_edx_services: false
    ENABLE_DATADOG: False
    ENABLE_SPLUNKFORWARDER: False
    ENABLE_NEWRELIC: False
  roles:
    - mysql
    - db_analytics
    - memcache
